### ISSUE TITLE
3.0.4 - Function Call Operator ( ) attempted on non-function

### ISSUE THREAD

**Issue by twig2let** [rokucommunity/rooibos#62]
Function `RBSFM_getIgnoredTestInfo` is not defined.

```
Function Call Operator ( ) attempted on non-function. (runtime error &he0) in pkg:/source/tests/rooibos/rooibosDist.brs(1779)
1779:   ignoredInfo = RBSFM_getIgnoredTestInfo()
Backtrace:
#3  Function rbs_logger_printstatistic(statobj As Object) As Void
   file/line: pkg:/source/tests/rooibos/rooibosDist.brs(1779)
#2  Function rbs_tr_run() As Void
   file/line: pkg:/source/tests/rooibos/rooibosDist.brs(2026)
#1  Function rooibos__init() As Dynamic
   file/line: pkg:/source/tests/rooibos/rooibosDist.brs(39)
#0  Function main(args As Dynamic) As Dynamic
   file/line: pkg:/source/Main.brs(6)
```
